### ISSUE TITLE
Addon doesn't work on Windows

### ISSUE THREAD

**Issue by dwickern** [timmfin/broccoli-webpack-cached#12]
Building from Windows command-line results in this error:
```
C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\memory-fs\lib\MemoryFileSystem.js:44
			throw new MemoryFileSystemError(errors.code.EINVAL, path);
			^
Error: invalid argument
    at pathToArray (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)
    at MemoryFileSystem.meta (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\memory-fs\lib\MemoryFileSystem.js:61:13)
    at MemoryFileSystem.statSync (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\memory-fs\lib\MemoryFileSystem.js:76:21)
    at C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\index.js:237:25
    at Array.forEach (native)
    at allMemoryFSFiles (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\index.js:230:8)
    at C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\index.js:184:40
    at Compiler.<anonymous> (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\webpack\lib\Compiler.js:195:14)
    at MemoryFileSystem.writeFile (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\memory-fs\lib\MemoryFileSystem.js:314:9)
    at Compiler.writeFile (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\webpack\lib\Compiler.js:296:25)
    at Compiler.emitRecords (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\webpack\lib\Compiler.js:289:51)
    at Compiler.<anonymous> (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\webpack\lib\Compiler.js:188:11)
    at C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\webpack\lib\Compiler.js:276:11
    at Compiler.applyPluginsAsync (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\tapable\lib\Tapable.js:60:69)
    at Compiler.afterEmit (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\webpack\lib\Compiler.js:273:8)
    at Compiler.<anonymous> (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\webpack\lib\Compiler.js:268:14)
    at C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\async\lib\async.js:52:16
    at Object.async.forEachOf.async.eachOf (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\async\lib\async.js:236:30)
    at Object.async.forEach.async.each (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\async\lib\async.js:209:22)
    at Compiler.emitFiles (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\webpack\lib\Compiler.js:236:20)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\memory-fs\lib\MemoryFileSystem.js:283:10)
    at Compiler.<anonymous> (C:\TeamCity\buildAgent\work\3ab5beb59bf00b60\ui\node_modules\broccoli-webpack-cached\node_modules\webpack\lib\Compiler.js:230:25)
```

Apparently caused by using `/` as the root path when memory-fs expects `C:\` on Windows (or some arbitrary drive letter).

**Comment by timmfin** [comment]
Oh, bummer. I have never run this on windows. And unfortunately, I'm not using broccoli any more so don't plan on continuing to maintain this.

In theory this should be a straightforward fix to provide a different root for `memory-fs` when on  windows. I wish you luck.
